import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class CityService {
  constructor() {}

  getCities(): any[] {
    return [
      {
        nameAr: "ينبع النخل",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "ينبع",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        "longitude": 24.0943,
        "latitude": 38.0493,
      },
      {
        nameAr: "وادى الدواسر",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "نفي",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "نجران",
        nameEn: "",
        district: "منطقة نجران",
        "longitude": 17.4917,
        "latitude": 44.1322,
      },
      {
        nameAr: "مكة المكرمة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: 21.4225,
        latitude: 39.8261,
      },
      {
        nameAr: "مرات",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "مدينة بريدة",
        nameEn: "",
        district: "منطقة القصيم",
        longitude: "26.358458",
        latitude: "43.980784",
      },
      {
        nameAr: "محائل عسير",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "لينة",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "قرية العليا",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "عيون الجواء",
        nameEn: "",
        district: "منطقة القصيم",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "عنيزة",
        nameEn: "",
        district: "منطقة القصيم",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "عفيف",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "عسير ",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "عرعر",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        "longitude": 30.9833,
        "latitude": 41.0167,
      },
      {
        nameAr: "ظلم",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "طلعة التمياط",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "طريف",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "طبرجل",
        nameEn: "",
        district: "منطقة الجوف",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "ضرماء",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "صفوى",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "شقراء",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "شعبة نصاب",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "سيهات",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "سدير الدلم",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "سبت العلايه",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "ساجر",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "روضة بن هباس",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "رنية",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "رماح",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "رفحاء",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "رأس  تنورة",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "رابغ",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "خيبر",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "خميس  مشيط",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "خليص",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "حوطة سدير",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "حوطة بني تميم",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "حفر الباطن",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 28.4337,
        "latitude": 45.9601,
      },
      {
        nameAr: "حريملاء",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "حائل",
        nameEn: "",
        district: "منطقة حائل",
        "longitude": 27.5236,
        "latitude": 41.7001,
      },
      {
        nameAr: "جده",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: 21.5428,
        latitude: 39.1728,
      },
      {
        nameAr: "جازان",
        nameEn: "",
        district: "منطقة جازان",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "ثول",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "ثادق",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "تيماء",
        nameEn: "",
        district: "منطقة تبوك",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "تمير",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "تربة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "تبوك",
        nameEn: "",
        district: "منطقة تبوك",
        "longitude": 28.3838,
        "latitude": 36.555,
      },
      {
        nameAr: "تاروت",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "بيشه",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "بلجرشي",
        nameEn: "",
        district: "منطقة الباحة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "بقيق",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "بريدة",
        nameEn: "",
        district: "منطقة القصيم",
        "longitude": 26.3333,
        "latitude": 43.9667,
      },
      {
        nameAr: "بدر",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "بحرة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "أملج",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "أضم الحلى",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "أبي عريش",
        nameEn: "",
        district: "منطقة جازان",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "أبها",
        nameEn: "",
        district: "منطقة عسير",
        "longitude": 18.2167,
        "latitude": 42.5,
      },
      {
        nameAr: "الوجه",
        nameEn: "",
        district: "منطقة تبوك",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الهياثم",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الهفوف",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 25.3608,
        "latitude": 49.5997,
      },
      {
        nameAr: "النعيرية",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "المهد",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "المزاحمية",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "المدينة المنورة",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        "longitude": 24.4667,
        "latitude": 39.6,
      },
      {
        nameAr: "المخواة",
        nameEn: "",
        district: "منطقة الباحة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "المجمعة",
        nameEn: "",
        district: "منطقة الرياض",
        "longitude": 25.9039,
        "latitude": 45.3456,
      },
      {
        nameAr: "المجاردة",
        nameEn: "",
        district: "منطقة عسير",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الليث",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الكامل",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "القويعية",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "القوز",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "القنفذة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "القطيف",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 26.5196,
        "latitude": 50.0115,
      },
      {
        nameAr: "القصب",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "القريات",
        nameEn: "",
        district: "منطقة الجوف",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الغاط",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "العيص",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "العويقيلة",
        nameEn: "",
        district: "منطقة الحدود الشمالية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "العلا",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "العرضية الجنوبية",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الظهران",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الطائف",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        "longitude": 21.2667,
        "latitude": 40.4167,
      },
      {
        nameAr: "الصويدرة",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الشعيبة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الشعبة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "السليل",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الزلفي",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الرياض",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "24.713535",
        latitude: "46.675437",
      },
      {
        nameAr: "الرويضة",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الدوادمي",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الدمام",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 26.4333,
        "latitude": 50.1,
      },
      {
        nameAr: "الدلم",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الخفجي",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الخرمة",
        nameEn: "",
        district: "منطقة مكة المكرمة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الخرج",
        nameEn: "",
        district: "منطقة الرياض",
        "longitude": 24.1556,
        "latitude": 47.312,
      },
      {
        nameAr: "الخبر",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 26.3,
        "latitude": 50.2167,
      },
      {
        nameAr: "الحناكية",
        nameEn: "",
        district: "منطقة المدينة المنورة",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الجوف",
        nameEn: "",
        district: "منطقة الجوف",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الجمش",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الجبيل",
        nameEn: "",
        district: "المنطقة الشرقية",
        "longitude": 27.0046,
        "latitude": 49.646,
      },
      {
        nameAr: "البجادية",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الباحة",
        nameEn: "",
        district: "منطقة الباحة",
        "longitude": 20.0129,
        "latitude": 41.4677,
      },
      {
        nameAr: "الأحساء",
        nameEn: "",
        district: "المنطقة الشرقية",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الافلاج",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
      {
        nameAr: "الارطاوية",
        nameEn: "",
        district: "منطقة الرياض",
        longitude: "",
        latitude: "",
      },
    ];
  }

  getCityByName(name: string): any {
    let cities = this.getCities();
    let city = cities.find((c) => c.nameAr === name || c.nameEn === name);

    return city;
  }

  getCitiesByDistrict(districtName: string): any[] {
    let cities = this.getCities();
    let selectedCities = cities.filter((c) => c.district === districtName);
    return selectedCities;
  }
}
